[project]
name = "speech-in"
version = "0.1.0"
description = "Speech input module using openWakeWord and Faster Whisper"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper==1.2.1",
    "numpy==1.26.4",
    "openwakeword==0.6.0",
    "pyaudio==0.2.14",
]
